In [1]:
import torch

In [2]:
import numpy

In [2]:
!nvidia-smi

Thu Apr 11 19:53:41 2024       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 546.33                 Driver Version: 546.33       CUDA Version: 12.3     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                     TCC/WDDM  | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  NVIDIA GeForce GTX 1650 Ti   WDDM  | 00000000:01:00.0 Off |                  N/A |
| N/A   44C    P8               5W /  50W |      0MiB /  4096MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

In [3]:
torch.__version__

'2.2.2+cu118'

In [13]:
tensor_2d=torch.randn(3,4)
print(tensor_2d)

tensor([[ 0.7044, -1.9895, -0.5713,  2.2074],
        [-0.8689,  2.6444, -0.2166,  0.5793],
        [-0.6603, -0.1301,  0.3483,  0.9142]])


In [6]:
tensor_3d = torch.randn(3,4,4)
print(tensor_3d)

tensor([[[ 0.4980, -1.1213,  0.8681,  0.0690],
         [ 0.1101, -0.0040, -0.3245,  0.8148],
         [-1.2221, -0.9965, -0.6338, -0.4549],
         [ 0.3434, -2.0014,  0.1015, -0.0488]],

        [[ 0.7334,  0.2307, -1.4744,  0.2688],
         [-1.3045, -2.6780, -0.7388, -0.2497],
         [ 0.6863,  1.1443, -0.7264, -0.6090],
         [ 0.0853,  0.9430,  0.2610,  1.3865]],

        [[ 0.6747,  0.3728, -0.8328, -0.8154],
         [ 0.0233, -0.7216, -0.4419, -0.5633],
         [-0.1662,  0.4013, -0.6063,  0.9924],
         [ 0.8392, -0.2432, -0.4333, -1.4673]]])


In [7]:
tensor_4d = torch.randn(3,4,4,2)
print(tensor_4d)

tensor([[[[-1.1318,  1.2299],
          [ 0.3406,  0.4462],
          [-1.2184, -0.2115],
          [-1.2673, -0.1468]],

         [[ 0.1440, -0.4298],
          [-0.4767, -0.3964],
          [ 2.3003,  0.3592],
          [ 0.2479, -1.0581]],

         [[ 0.6854,  0.8617],
          [ 1.3749,  0.4624],
          [ 0.2430, -0.2467],
          [-1.1528, -0.4697]],

         [[-0.4898, -1.3465],
          [-0.8691,  1.3375],
          [-0.9554, -1.5040],
          [ 1.0011, -0.4135]]],


        [[[ 0.0802, -1.1999],
          [-0.5889,  1.8381],
          [-1.2614, -0.9306],
          [ 1.0701,  2.2177]],

         [[ 1.1098, -0.8051],
          [-0.4834, -0.4614],
          [ 0.1034, -0.9153],
          [-1.1904,  0.0993]],

         [[ 0.2549,  0.5328],
          [ 0.4385,  1.5184],
          [ 0.4287,  0.4585],
          [-0.6122,  0.0415]],

         [[ 1.0153, -1.4261],
          [ 0.4283, -0.0098],
          [-1.1445,  1.0852],
          [-0.2240, -0.0523]]],


        [[[ 0.7543, 

In [8]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [10]:
#create tensors from numpy array
np1=numpy.random.rand(3,4)
print(np1)

[[0.15251461 0.61111841 0.77625736 0.37838442]
 [0.86042058 0.18644291 0.54722575 0.67117877]
 [0.12382732 0.35855724 0.40660435 0.22925934]]


In [11]:
np_to_ten=torch.tensor(np1)
print(np_to_ten)

tensor([[0.1525, 0.6111, 0.7763, 0.3784],
        [0.8604, 0.1864, 0.5472, 0.6712],
        [0.1238, 0.3586, 0.4066, 0.2293]], dtype=torch.float64)


In [16]:
tensor_3d.dtype

torch.float32

In [17]:
tensor_3d.is_cuda

False

create a tensor on gpu

In [18]:
gpu=torch.device('cuda:0')

In [19]:
tensor_gpu=torch.randn([3,4],dtype=torch.float64,device=gpu)

In [20]:
tensor_gpu.is_cuda

True